## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [4]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("weather_database/WeatherPy_Database.csv")
city_data_df.head(10)

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Current Weather Description
0,0,Albany,42.6001,-73.9662,45.09,64,100,1.01,US,2021-12-10 18:40:50,overcast clouds
1,1,Northam,51.0333,-4.2167,45.61,72,14,18.30,GB,2021-12-10 18:40:27,few clouds
2,2,Bambous Virieux,-20.3428,57.7575,78.22,78,40,5.75,MU,2021-12-10 18:31:47,scattered clouds
3,3,Metro,-5.1131,105.3067,73.60,97,100,7.31,ID,2021-12-10 18:41:27,overcast clouds
4,4,Ponta Do Sol,32.6667,-17.1000,66.70,77,26,9.78,PT,2021-12-10 18:40:54,scattered clouds
5,5,Rikitea,-23.1203,-134.9692,76.10,70,23,17.29,PF,2021-12-10 18:40:49,few clouds
6,6,Beloha,-25.1667,45.0500,75.13,81,52,8.46,MG,2021-12-10 18:36:01,broken clouds
7,7,Butaritari,3.0707,172.7902,82.11,76,100,13.42,KI,2021-12-10 18:41:04,light rain
8,8,Lodwar,3.1191,35.5973,83.70,44,65,24.27,KE,2021-12-10 18:41:28,broken clouds
9,9,Puerto Ayora,-0.7393,-90.3518,76.96,92,96,5.01,EC,2021-12-10 18:37:29,overcast clouds

In [5]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [12]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Current Weather Description
2,2,Bambous Virieux,-20.3428,57.7575,78.22,78,40,5.75,MU,2021-12-10 18:31:47,scattered clouds
5,5,Rikitea,-23.1203,-134.9692,76.10,70,23,17.29,PF,2021-12-10 18:40:49,few clouds
6,6,Beloha,-25.1667,45.0500,75.13,81,52,8.46,MG,2021-12-10 18:36:01,broken clouds
7,7,Butaritari,3.0707,172.7902,82.11,76,100,13.42,KI,2021-12-10 18:41:04,light rain
8,8,Lodwar,3.1191,35.5973,83.70,44,65,24.27,KE,2021-12-10 18:41:28,broken clouds
9,9,Puerto Ayora,-0.7393,-90.3518,76.96,92,96,5.01,EC,2021-12-10 18:37:29,overcast clouds
15,15,Cabo San Lucas,22.8909,-109.9124,82.51,56,84,4.00,MX,2021-12-10 18:40:50,broken clouds
16,16,Avarua,-21.2078,-159.7750,78.85,83,100,2.30,CK,2021-12-10 18:41:29,overcast clouds
19,19,Eyl,7.9803,49.8164,76.03,71,6,19.73,SO,2021-12-10 18:39:20,clear sky
20,20,Arraial Do Cabo,-22.9661,-42.0278,80.56,65,20,12.66,BR,2021-12-10 18:40:46,few clouds

In [13]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.isnull().sum()

City_ID                        0
City                           0
Lat                            0
Lng                            0
Max Temp                       0
Humidity                       0
Cloudiness                     0
Wind Speed                     0
Country                        0
Date                           0
Current Weather Description    0
dtype: int64

In [14]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
preferred_cities_df.dropna()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Current Weather Description
2,2,Bambous Virieux,-20.3428,57.7575,78.22,78,40,5.75,MU,2021-12-10 18:31:47,scattered clouds
5,5,Rikitea,-23.1203,-134.9692,76.10,70,23,17.29,PF,2021-12-10 18:40:49,few clouds
6,6,Beloha,-25.1667,45.0500,75.13,81,52,8.46,MG,2021-12-10 18:36:01,broken clouds
7,7,Butaritari,3.0707,172.7902,82.11,76,100,13.42,KI,2021-12-10 18:41:04,light rain
8,8,Lodwar,3.1191,35.5973,83.70,44,65,24.27,KE,2021-12-10 18:41:28,broken clouds
...,...,...,...,...,...,...,...,...,...,...,...
677,677,Ternate,0.8000,127.4000,81.39,82,100,7.90,ID,2021-12-10 18:38:32,overcast clouds
678,678,Quelimane,-17.8786,36.8883,82.35,83,20,8.99,MZ,2021-12-10 18:45:55,few clouds
682,682,Morgan City,29.6994,-91.2068,82.40,78,90,20.71,US,2021-12-10 18:45:56,overcast clouds
689,689,Makokou,0.5738,12.8642,76.91,71,98,1.45,GA,2021-12-10 18:46:03,overcast clouds
691,691,Itupiranga,-5.1347,-49.3267,89.92,69,98,2.13,BR,2021-12-10 18:46:04,overcast clouds

In [16]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Weather Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Weather Description,Lat,Lng,Hotel Name
2,Bambous Virieux,MU,78.22,scattered clouds,-20.3428,57.7575,
5,Rikitea,PF,76.10,few clouds,-23.1203,-134.9692,
6,Beloha,MG,75.13,broken clouds,-25.1667,45.0500,
7,Butaritari,KI,82.11,light rain,3.0707,172.7902,
8,Lodwar,KE,83.70,broken clouds,3.1191,35.5973,
9,Puerto Ayora,EC,76.96,overcast clouds,-0.7393,-90.3518,
15,Cabo San Lucas,MX,82.51,broken clouds,22.8909,-109.9124,
16,Avarua,CK,78.85,overcast clouds,-21.2078,-159.7750,
19,Eyl,SO,76.03,clear sky,7.9803,49.8164,
20,Arraial Do Cabo,BR,80.56,few clouds,-22.9661,-42.0278,

In [19]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():

    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")
hotel_df.head(10)

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

,City,Country,Max Temp,Current Weather Description,Lat,Lng,Hotel Name
2,Bambous Virieux,MU,78.22,scattered clouds,-20.3428,57.7575,Casa Tia Villa
5,Rikitea,PF,76.10,few clouds,-23.1203,-134.9692,People ThankYou
6,Beloha,MG,75.13,broken clouds,-25.1667,45.0500,
7,Butaritari,KI,82.11,light rain,3.0707,172.7902,Isles Sunset Lodge
8,Lodwar,KE,83.70,broken clouds,3.1191,35.5973,Solmar Gracious Hotel
9,Puerto Ayora,EC,76.96,overcast clouds,-0.7393,-90.3518,Finch Bay Galapagos Hotel
15,Cabo San Lucas,MX,82.51,broken clouds,22.8909,-109.9124,Hotel Tesoro Los Cabos
16,Avarua,CK,78.85,overcast clouds,-21.2078,-159.7750,Paradise Inn
19,Eyl,SO,76.03,clear sky,7.9803,49.8164,Amiin Hotel
20,Arraial Do Cabo,BR,80.56,few clouds,-22.9661,-42.0278,Pousada Porto Praia

In [34]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.dropna()
clean_hotel_df

,City,Country,Max Temp,Current Weather Description,Lat,Lng,Hotel Name
2,Bambous Virieux,MU,78.22,scattered clouds,-20.3428,57.7575,Casa Tia Villa
5,Rikitea,PF,76.10,few clouds,-23.1203,-134.9692,People ThankYou
6,Beloha,MG,75.13,broken clouds,-25.1667,45.0500,
7,Butaritari,KI,82.11,light rain,3.0707,172.7902,Isles Sunset Lodge
8,Lodwar,KE,83.70,broken clouds,3.1191,35.5973,Solmar Gracious Hotel
...,...,...,...,...,...,...,...
677,Ternate,ID,81.39,overcast clouds,0.8000,127.4000,Sahid Bela Ternate Hotel
678,Quelimane,MZ,82.35,few clouds,-17.8786,36.8883,Hotel Flamingo
682,Morgan City,US,82.40,overcast clouds,29.6994,-91.2068,Hampton Inn & Suites Morgan City
689,Makokou,GA,76.91,overcast clouds,0.5738,12.8642,Motel des voyageurs
691,Itupiranga,BR,89.92,overcast clouds,-5.1347,-49.3267,Hotel Panorama

In [36]:
# 8a. Create the output File (CSV)
output_data_file = "Vacation_Search/WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [37]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [38]:
# 11a. Add a marker layer for each city to the map. 
max_temp = clean_hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))